---
title: "Research Goals"
author: "V & B"
date: "10/15/2020"
output: html_document
---

As a municipal assessor, it is the responsibility of the Milwaukee Assessor’s Office to ensure that
property assessments are a fair and equitable reflection of the fair market value of each property.
While the Assessor’s Office does not use racial or socioeconomic demographics as factors in our
analysis, we have a duty to understand the impact of the real estate market and our assessments on
the various communities within the city. This duty is even more important in the context of
Milwaukee’s history of segregation and racial injustice in the housing profession. Communities of
color and low income communities can be disproportionately affected, intentionally or not, by
choices made in the overall real estate market and by the valuation methods of the Assessor’s
Office.


Goals: The goals of this project include:
    1. Identifying how market trends differentially impact communities of color and varying
       socioeconomic status; and
      
    2. Determining whether Milwaukee property assessments change disproportionately
       according to demographic factors.
       
       
Do we have adequate demograpgic information for milwaukee?

  - white populations
  - black populations
  - non white populations
  - hispanic populations
  
  x do not yet have other races * need to see if there is a significant portion
  
  
What are other measures of socio economic status
  - median income
  - renter percentage / home ownership
  
  
  
  
Notes on Ratio-Income Poverty Measure
Ratios below 100 percent of the poverty level are below the official poverty definition. Ratios below 50 percent of the poverty level, which means that the income is less than half the poverty threshold, have been described as 'severe poverty'. While those above 100 percent the poverty level, but below 125 percent have been described as 'near poverty'. A larger percentage above the poverty level means the category contains people with higher incomes.
  
  


####### Notes from Main Paper

my regressions will include demographic observables at the Census block group level, as well as fixed effects for cities, parcel districts, school attendance zones, and/or Census tracts.

 I include log median sale price, median age, log median acreage, median stories, and the percentages of
homes that have above or below “average” CDU (depreciation)25 – for each Census block group

*** For each Group he calculates
  - log median sale price
  - median age
  - log median acreage
  - median stories
  - below average CDU (depreciation)
  
  
  
 Faulk and Hicks (2015: 6) – studying the whole state of Indiana – find
mean ratios of 2.9287 and 0.8752 for the lowest- and highest priced homes (respectively) in their untrimmed sample, and
mean ratios of 1.4654 and 0.8597 for the lowest- and highest-priced homes in their trimmed sample. Relative to the
variation that Faulk and Hicks found, our ratios of 0.9362 and 0.89 for the lowest- and highest-priced homes   
  
  
  *** We see the same trends noted here 
    - Mean:    .942 - .871
    - Median:  .953 - .874
  
  
 we saw that the effect of median neighborhood price was the opposite of individual home sale price: a
higher median price was associated with higher assessment and taxation, while a high sale price was associated with lower
assessment and taxation. If we control for these two variables simultaneously, the coefficients will be difficult to interpret.


Therefore, in our regressions, we replace log sale price with the percent deviation of a house’s individual sale price from
its neighborhood’s median sale.

Thus, rather than separately controlling for individual and average sale prices, we controlfor the average sale price (of each Census block group) and the individual deviations from the average

  *** We seem the same trends ## EXACT SAME
  *** Ought to take the same percausion & use deviation from median
  *** He controlled for average sale price of grouping & individual deviations from the average
  
  
  
  
  
  
Because our variables are all
measured in different units, all coefficients are standardized. Thus, a one standard deviation change in the independent
variable is associated with a beta standard deviation change in the dependent variable. 



  *** Need to scale all predictors
  
  
  
  
  ******
  Therefore, in our regressions, we replace log sale price with the percent deviation of a house’s individual sale price from
its neighborhood’s median sale. Thus, rather than separately controlling for individual and average sale prices, we controlfor the average sale price (of each Census block group) and the individual deviations from the average. This should help
us determine whether property taxes are progressive or regressive with respect to sale price.
  
  ****** Need to replace log sale price with the percent deviation of a house's individual sale price from it's neighborhood median sale
  
  
  
  ***
  Thus, a one standard deviation change in the independent
variable is associated with a beta standard deviation change in the dependent variable. To estimate whether property
taxation is progressive or regressive with respect to sale price, we look to the coefficients on neighborhood median sale
price, an individual home’s percent deviation above, and percent deviation below
  
  
  
####################### FINDINGS FOR COLLIN #####################  
  
 we controlfor the average sale price (of each Census block group) and the individual deviations from the average


The effect of median neighborhood price is the opposite of individual home sale price

    - a higher median price was associated with higher assessment
    
    - a high sale price is associated is assocaited with a lower assessment
  
  
    Thus, we will control for average sale price of each tract
      & the individual deviations from the average
      
    Hopefully this will allow us to determine whether property taxes are
    progressive or regressive with respect to sale price
    
      - Look to beta coefficients on the neighborhood median sale price, the individual home's percent
        deviation below & above


Interpretations of Coefficients

    A one standard deviation change in the independent variable is associated with a beta
    standard deviation change in the dependent variable
    
    
For Model 1

    Log Median Income is significant
       - A one standard deviation increase in LogMedianIncome is associated with a 0.12481 
         standard deviation increase in the assessment ratio
         
      - Residents of higher-income neighborhoods are taxed at higher effective rates
         
      Interpretation: Difference between an annual property tax bill of $1000 & 
      
      1000 + (1000*sqrt(var(resdata$atsratio)) * 0.12)
  

  
  

  
################# QUESTIONS FOR COLLIN ##########################

In fact, I find that homes in black neighborhoods of Fulton County are consistently under-assessed. This may merely
indicate lack of discrimination. On the other hand, this could be evidence of a different problem. Banks often rely on
county assessments when evaluating mortgage applications. If homes in black neighborhoods are under-assessed,
applicants may face difficulty accessing credit.

************** Future studies should combine data on county assessments with data on
    private assessments and loans to determine whether county under-assessment impedes access to credit, controlling for sale
    price.
